Traceback (most recent call last):
  File "/Users/tchun/opt/anaconda3/envs/class_ml/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/tchun/opt/anaconda3/envs/class_ml/lib/python3.12/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tchun/opt/anaconda3/envs/class_ml/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tchun/opt/anaconda3/envs/class_ml/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/tchun/opt/anaconda3/envs/class_ml/lib/python3.12/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/tchun/opt/anaconda3/envs/class_ml/lib/python3.12/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/tchun/opt/anaconda3/envs/class_ml/lib/python3.12/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor

# Creating a DataFrame with an additional feature 'experience'
df = pd.DataFrame()
df['ID'] = ['A1', 'B2', 'C3', 'D4', 'E5', 'F6']
df['age'] = [25, 32, 47, 51, 30, 38]
df['education'] = ['bachelor', 'master', 'phd', 'phd', 'bachelor', 'highschool']
df['experience'] = [2, 15, 8, 4, 14, 15]  # New feature 'experience'
df['salary'] = [48000, 80000, 75000, 82000, 72000, 56000]
display(df)

n = df.shape[0]
X = df[['age', 'education', 'experience']].copy()

# Converting categorical data to numerical
X.loc[X['education'] == 'bachelor', 'education'] = 1
X.loc[X['education'] == 'master', 'education'] = 2
X.loc[X['education'] == 'phd', 'education'] = 3
X.loc[X['education'] == 'highschool', 'education'] = 0
y = df['salary']
display(X)
display(y)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[1;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[0;32m----> 3[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mtree[39;00m [38;5;28;01mimport[39;00m DecisionTreeRegressor
[1;32m      5[0m [38;5;66;03m# Creating a DataFrame with an additional feature 'experience'[39;00m
[1;32m      6[0m df [38;5;241m=[39m pd[38;5;241m.[39mDataFrame()

[0;31mModuleNotFoundError[0m: No module named 'sklearn'

